### ISSUE TITLE
YouTube crashes with "RESULT_CODE_UNINSTALL_USER_CANCEL" for some videos

### ISSUE THREAD

**Issue by elsnorrow** [macchrome/macstable#17]
Not sure why #16 was closed. But will elaborate a bit more. The issue occurs when watching certain YouTube videos. Example video: https://www.youtube.com/watch?v=HgzGwKwLmgM. The error is as follows:
![Screenshot 2020-08-17 at 21 25 36](https://user-images.githubusercontent.com/1223936/90436009-3bd73380-e0d0-11ea-82b3-126999b6f541.png)

I'm receiving the exact same error as described in Issue #15. I tried both:

- Chromium.app.ungoogled-84.0.4147.125-nopolly-AV1-VPx.zip

- Chromium.app.ungoogled-84.0.4147.125.zip

The issue occurs on both version (where it is supposed to be fixed in nopolly-AV1-VPx). Let me know if you need any additional information. Thanks in advance!

**Comment by macchrome** [comment]
This is an optimised release of ungoogled Chromium for macOS; it might not be suitable for all: a conventional build may be found at https://ungoogled-software.github.io/ungoogled-chromium-binaries/

Video playback issues will not be considered unless:

 - https://tools.woolyss.com/html5-audio-video-tester/ has been consulted and failures noted.
 - macOS version, GPU (integrated/discrete) and CPU are declared.
