### ISSUE TITLE
enabling enable_hangout_services_extension for the 

### ISSUE THREAD

**Issue by anantshri** [macchrome/macstable#18]
I have come to this repository via https://github.com/mtslzr/homebrew-marmaduke-chromium 
There are three versions release in it

marmaduke-chromium - Includes Google Sync and wildvine (DRM for Netflix).
marmaduke -chromium-nosync - Does not include Google Sync nor wildvine.
marmaduke-chromium-ungoogled - ungoogled-chromium (Eloston/ungoogled-chromium/)

This request is specifically for item 1. For this version can we enabled "enable_hangout_services_extension" this would allow the users to use google meet screen share feature. This is the only build i have found so far which allows DRM content etc and is the only feature missing is this one screensharing feature in hangout/ meet. rest all the other types i can fully understand not enabling this but for this version making the flag as an entry would help.

**Comment by macchrome** [comment]
If the next build builds cleanly, I will enable  "enable_hangout_services_extension".

**Comment by anantshri** [comment]
just a note. I can confirm the newer builds are able to do screen share in hangout calls.
