### ISSUE TITLE
ungoogled version can't install extensions?

### ISSUE THREAD

**Issue by ballo** [macchrome/macstable#20]
I'm not sure if this is by design or not, but the ungoogled marmaduke builds cannot use the chrome web store as the "Add to chrome" button is missing.

**Comment by entepe85** [comment]
Several Google URLs are blocked by default as part of the Ungoogled patches. You can, however, use the following extension (install it manually) to restore web store functionality:
https://github.com/NeverDecaf/chromium-web-store
