### ISSUE TITLE
Can't share screen

### ISSUE THREAD

**Issue by csrutil** [macchrome/macstable#25]
I can't share the screen, there is a same issue #18, but its not working for me. is there any way to enable that? Thank you so much!

![Screen Shot 2021-04-20 at 8 48 10 AM](https://user-images.githubusercontent.com/6078291/115320873-3f6a0f80-a1b5-11eb-8245-031532a1a64c.png)

$ ~ sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91

Version 89.0.4389.72 (Official Build) (x86_64)

**Comment by macchrome** [comment]
I will incorporate screen sharing in the next release.

**Comment by csrutil** [comment]
Thank you @macchrome!

**Comment by csrutil** [comment]
Hey @macchrome, thank you for all your hard work! I downloaded the sync version and it seems `share screen` is not working again.

OS
```bash
mini ~/Code sw_vers
ProductName:  macOS
ProductVersion: 12.6
BuildVersion: 21G115

```

Chromium version
```
Chromium  106.0.5249.61 (Official Build) (x86_64) 
Revision  511755355844955cd3e264779baf0dd38212a4d0-refs/branch-heads/5249@{#569}
OS  macOS Version 12.6 (Build 21G115)
JavaScript  V8 10.6.194.12
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Command Line  /Applications/Chromium.app/Contents/MacOS/Chromium --enable-features=PlatformHEVCDecoderSupport --flag-switches-begin --enable-experimental-web-platform-features --flag-switches-end
```

https://github.com/macchrome/macstable/releases/tag/v106.5249.061-M106.0.5249.61-r1036826-macOS

![image](https://user-images.githubusercontent.com/6078291/197091118-9b79e1e1-b474-4f12-936a-e70cb3f60c9e.png)
