### ISSUE TITLE
Apple Silicon version for v91

### ISSUE THREAD

**Issue by inprealpha** [macchrome/macstable#26]
Hi! I noticed that v91 is only for intel. Can an apple silicon be built too?

Thanks for making this! v90 works great on my m1, so just thought that v91 would be nice.

**Comment by inprealpha** [comment]
Saw that the issue was closed, is there an arm64 version available somewhere? @macchrome

**Comment by fabd** [comment]
Ditto. A non "ungoogled" version of Chromium for ARM64 would be very appreciated.
