### ISSUE TITLE
96+ releases will only run on Big Sur or later

### ISSUE THREAD

**Issue by mcringbearer** [macchrome/macstable#32]
The 96.x releases will crash on launch on macOS versions prior to Big Sur.  This includes Catalina, Mojave, and High Sierra.  I've been told I can fix this by compiling my own version on the macOS I wish to run on.  I am not a developer, completely beyond me.  I've used Marmaduke releases for years, I appreciate greatly the time and effort put in to providing these builds.  I hope you will consider resolving this if possible. thank you

**Comment by mcringbearer** [comment]
Sir, I have an older MacMini running Mojave.  I am happy to donate to you if it helps solve this problem by having an older system to create a build on, which I guess is the problem?  They are super slow, but even if it takes all day to build, it shouldn't be an issue.  If interested, let me know.

**Comment by vladimir-pachnik** [comment]
The specific error:
```
Application Specific Information:
dlopen /Applications/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/96.0.4664.93/Chromium Framework: dlopen(/Applications/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/96.0.4664.93/Chromium Framework, 261): Symbol not found: _kCGColorSpaceITUR_2100_PQ
  Referenced from: /Applications/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/96.0.4664.93/Chromium Framework
  Expected in: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
 in /Applications/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/96.0.4664.93/Chromium Framework.
 ```
