### ISSUE TITLE
macOS 10.14.1 claims that v70.0.3538.102 sync build is broken

### ISSUE THREAD

**Issue by cpbotha** [macchrome/macstable#4]
When I unzip the 70.0.3538.102 sync build and try to run it, macOS says:

"Chromium is damaged and can't be opened. You should move it to the Trash."

I double-checked the published SHA1, it is correct. I am able to unzip and run the NOSYNC binary.

**Comment by macchrome** [comment]
Try:

https://github.com/macchrome/macstable/releases/download/v70.0.3538.102-r587811-macOS/Chromium.70.0.3538.102.rev1.sync.app.zip

**Comment by cpbotha** [comment]
This rev1 is working!

1. Can I use this build and download location for the homebrew cask?
2. What was the problem with the previous one?

**Comment by macchrome** [comment]
1. Of course you can! I've also updated the no-sync version.

2.  I changed build systems from 10.14 to 10.13: the bespoke compiler was probably not up to date. Also, I did not check the compressed package.
