### ISSUE TITLE
Chromium v106.0.5249.61-r1036826 on macos 10.13.6 reports illegal instruction 4 on launch

### ISSUE THREAD

**Issue by TrainzLuvr** [macchrome/macstable#41]
interwebs says it might not have been compiled with **-mmacosx-version-min=10.x**

**Comment by macchrome** [comment]
CPU must support AVX .

**Comment by TrainzLuvr** [comment]
This was on an iMac 27" Core i7.

Previous ungoogled version 103 had no problems running, why all of a sudden requirement for AVX?

**Comment by TrainzLuvr** [comment]
Please don't leave us, users with older macs out in the cold, we have no where else to go. :)

**Comment by macchrome** [comment]
106.0.5249.91 is non-AVX
