### ISSUE TITLE
M1 / ARM64 release

### ISSUE THREAD

**Issue by petar-staynov-brandwatch** [macchrome/macstable#43]
Hello,
Is there any way to get builds for Apple Silicon (M1/M2)? 
Or some tips on how to build it? I'm talking about version with working sync.

**Comment by macchrome** [comment]
general instructions: https://chromium.googlesource.com/chromium/src/+/master/docs/mac_build_instructions.md

sync: https://github.com/Alex313031/Thorium

M1/M2: https://github.com/kramred/ungoogled-chromium-macos
