### ISSUE TITLE
How are you cross-compiling Chromium from Ubuntu for MacOS?

### ISSUE THREAD

**Issue by djd0723** [macchrome/macstable#44]
For about a year now, I’ve been searching nonstop for a way to cross-compile Chromium for macOS from a Linux server, but this is the first time I’ve actually seen someone successfully do it. If I just mirror the specs listed in the notes for each release, will I also be able to cross-compile Chromium for macOS from Ubuntu? Are there any other important details to cross-compile which aren’t listed in the notes for each release?

I’ve tried and failed more times than I can count to cross-compile Chromium for macOS from Ubuntu. I’d love to know how to do it if you don’t mind sharing. I’m currently using AWS EC2 instances to host a KVM with the Mac operating system installed onto it for compiling chromium remotely but it honestly stinks and I absolutely hate it. AWS only has one family of EC2 instances capable of running KVMs, called “Bare Metal” which end up requiring like 4-5x more time and money than a normal EC2 instance with Ubuntu installed. They’re ridiculously expensive, complete pieces of junk, and it’s the only option offered by Amazon for KVMs.

If you could help me cross-compile builds for macOS from a regular Ubuntu server, that would be a complete game-changer for me...

**Comment by macchrome** [comment]
It's relatively straight forward:

https://github.com/macchrome/winchrome/wiki/Ungoogled-Chromium-Cross-Compilation-Resources#chromium-linux-to-macos-cross-compilation-resources


(SDK used must correspond with version used for Chromium)
